2021-07-26 09:20:29,773 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Synchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 09:20:30,518 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Asynchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer member's generation is already stale, meaning it has already participated another rebalance and got a new generation. You can try completing the rebalance by calling poll() and then retry commit again
2021-07-26 09:20:30,517 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Asynchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 09:20:30,521 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Synchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 09:20:50,501 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Asynchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 09:20:50,502 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Synchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 09:20:50,503 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Synchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 09:20:50,505 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Asynchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer member's generation is already stale, meaning it has already participated another rebalance and got a new generation. You can try completing the rebalance by calling poll() and then retry commit again
2021-07-26 09:21:07,907 WARN [HikariPool-5 housekeeper] c.z.h.p.HikariPool [HikariPool.java:787] HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=11h6m43s163ms150µs1ns).
2021-07-26 13:22:39,361 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Asynchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 13:22:39,362 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Synchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 13:22:39,392 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Asynchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 13:22:39,393 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Synchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 13:36:39,352 WARN [HikariPool-5 housekeeper] c.z.h.p.HikariPool [HikariPool.java:787] HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=1h38m30s926ms38µs700ns).
2021-07-26 14:01:00,621 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Asynchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 14:01:00,622 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Synchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:01:15,027 WARN [HikariPool-5 housekeeper] c.z.h.p.HikariPool [HikariPool.java:787] HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=1m35s627ms709µs).
2021-07-26 14:10:58,171 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Asynchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 14:10:58,172 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Synchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:10:58,174 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-13, groupId=community-consumer-group] Asynchronous auto-commit of offsets {comment-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}, like-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}, follow-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 14:10:58,175 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-13, groupId=community-consumer-group] Synchronous auto-commit of offsets {comment-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}, like-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}, follow-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:10:58,175 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Asynchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 14:10:58,175 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Synchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:15:00,048 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:15:06,380 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:15:12,811 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:15:20,004 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:15:27,192 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:15:33,383 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:15:43,713 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:16:02,210 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:16:34,294 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:17:06,372 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:17:38,492 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:18:10,591 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:18:42,689 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:19:14,792 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:19:47,277 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:20:19,395 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:20:51,479 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:21:23,593 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:21:55,691 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:22:27,778 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:22:59,896 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:23:31,972 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:24:04,097 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:33:21,707 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Asynchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 14:33:21,707 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-13, groupId=community-consumer-group] Asynchronous auto-commit of offsets {comment-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}, like-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}, follow-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2021-07-26 14:33:21,707 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-14, groupId=community-consumer-group] Synchronous auto-commit of offsets {publish-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:33:21,707 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-13, groupId=community-consumer-group] Synchronous auto-commit of offsets {comment-0=OffsetAndMetadata{offset=2, leaderEpoch=0, metadata=''}, like-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}, follow-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:33:21,708 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1063] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Synchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
2021-07-26 14:33:21,728 WARN [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] o.a.k.c.c.i.ConsumerCoordinator [ConsumerCoordinator.java:1042] [Consumer clientId=consumer-community-consumer-group-15, groupId=community-consumer-group] Asynchronous auto-commit of offsets {delete-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}} failed: Offset commit cannot be completed since the consumer member's generation is already stale, meaning it has already participated another rebalance and got a new generation. You can try completing the rebalance by calling poll() and then retry commit again
2021-07-26 14:33:23,669 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:33:46,863 WARN [HikariPool-5 housekeeper] c.z.h.p.HikariPool [HikariPool.java:787] HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=9m20s789ms257µs400ns).
2021-07-26 14:33:55,793 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:34:27,908 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:35:00,003 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:35:32,116 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:36:04,208 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:36:36,287 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:37:08,397 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:37:40,482 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:38:12,595 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:38:44,684 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:39:16,773 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:39:48,894 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:40:20,989 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:40:53,096 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:41:25,200 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:41:57,305 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:42:29,384 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:43:01,460 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:43:33,591 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:44:05,678 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:44:37,787 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:45:09,885 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:45:41,983 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:46:14,079 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:46:46,179 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:47:18,294 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:47:50,380 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:48:22,494 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:48:54,562 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:49:26,663 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:49:58,777 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:50:30,868 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:51:02,988 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:51:35,058 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:52:07,171 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:52:39,281 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:53:11,363 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:53:43,460 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:54:15,568 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:54:47,685 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:55:19,786 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:55:51,870 WARN [lettuce-nioEventLoop-15-2] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:56:23,965 WARN [lettuce-nioEventLoop-15-3] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:56:56,077 WARN [lettuce-nioEventLoop-15-4] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:57:28,199 WARN [lettuce-nioEventLoop-15-5] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:58:00,265 WARN [lettuce-nioEventLoop-15-6] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:58:32,374 WARN [lettuce-nioEventLoop-15-7] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:59:04,469 WARN [lettuce-nioEventLoop-15-8] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:59:36,583 WARN [lettuce-nioEventLoop-15-1] i.l.c.p.ConnectionWatchdog [AbstractInternalLogger.java:151] Cannot reconnect to [localhost:6379]: Connection refused: no further information: localhost/127.0.0.1:6379
2021-07-26 14:59:59,241 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.geo.Point to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,242 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.geo.Point as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,242 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,242 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,243 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from interface org.springframework.data.elasticsearch.core.geo.GeoJson to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,243 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to interface org.springframework.data.elasticsearch.core.geo.GeoJson as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,243 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,243 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,244 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,244 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,244 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonLineString to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,244 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonLineString as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,245 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiLineString to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,245 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiLineString as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,246 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonPolygon to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,246 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonPolygon as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,246 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiPolygon to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,246 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiPolygon as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,247 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:270] Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonGeometryCollection to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,247 WARN [restartedMain] o.s.d.c.CustomConversions [CustomConversions.java:260] Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoJsonGeometryCollection as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2021-07-26 14:59:59,537 WARN [restartedMain] o.s.d.e.c.m.SimpleElasticsearchPersistentProperty [SimpleElasticsearchPersistentProperty.java:169] No DateFormat defined for property DiscussPost.createTime. Make sure you have a Converter registered for Date
2021-07-26 15:00:08,193 WARN [boundedElastic-1] o.s.b.a.r.RedisReactiveHealthIndicator [AbstractReactiveHealthIndicator.java:89] Redis health check failed
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1553)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1461)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1247)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1230)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:989)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:445)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:98)
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:320)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:211)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1459)
	... 15 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-07-26 15:00:08,216 WARN [http-nio-8080-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:10,273 WARN [http-nio-8080-exec-2] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:14,330 WARN [http-nio-8080-exec-3] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:16,383 WARN [http-nio-8080-exec-4] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:18,450 WARN [http-nio-8080-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:20,516 WARN [http-nio-8080-exec-6] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:22,573 WARN [http-nio-8080-exec-7] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:24,622 WARN [http-nio-8080-exec-8] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:26,677 WARN [http-nio-8080-exec-10] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:28,722 WARN [http-nio-8080-exec-9] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:30,787 WARN [http-nio-8080-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:32,840 WARN [http-nio-8080-exec-2] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:34,901 WARN [http-nio-8080-exec-3] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:36,949 WARN [http-nio-8080-exec-4] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:39,014 WARN [http-nio-8080-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:41,063 WARN [http-nio-8080-exec-6] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:43,107 WARN [http-nio-8080-exec-7] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:45,170 WARN [http-nio-8080-exec-8] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:47,238 WARN [http-nio-8080-exec-10] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:49,283 WARN [http-nio-8080-exec-9] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:52,376 WARN [http-nio-8080-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:54,434 WARN [http-nio-8080-exec-2] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:56,487 WARN [http-nio-8080-exec-3] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:00:58,541 WARN [http-nio-8080-exec-4] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:00,588 WARN [http-nio-8080-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:02,655 WARN [http-nio-8080-exec-6] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:04,705 WARN [http-nio-8080-exec-7] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:06,757 WARN [http-nio-8080-exec-8] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:08,812 WARN [http-nio-8080-exec-9] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:10,859 WARN [http-nio-8080-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:12,924 WARN [http-nio-8080-exec-2] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:14,984 WARN [http-nio-8080-exec-3] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:17,026 WARN [http-nio-8080-exec-4] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:19,084 WARN [http-nio-8080-exec-5] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:21,142 WARN [http-nio-8080-exec-6] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:23,182 WARN [http-nio-8080-exec-7] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:25,233 WARN [http-nio-8080-exec-10] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:27,290 WARN [http-nio-8080-exec-8] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:29,352 WARN [http-nio-8080-exec-9] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
2021-07-26 15:01:31,400 WARN [http-nio-8080-exec-1] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:207] Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379]
